---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(grid)
library(gridExtra)
datt <- as.matrix(read.csv("C:/Users/Hugh/Desktop/Riverlab/gw_by_obs_period.csv"), stringsAsFactors=FALSE, header=FALSE)
unbinned <- as.matrix(read.csv("C:/Users/Hugh/Desktop/Riverlab/gw_by_obs_period_unbinned.csv"), stringsAsFactors=FALSE, header=FALSE)
```


```{r}
period_to_date <- hash()
for (row in seq(1, nrow(unbinned), 1)){
  per <- unbinned[row, 6]
  date <- as.character(unbinned[row, 2])
  period_to_date[per] <- date
}
dates <- c()
for (per in keys(period_to_date)){
  dates <- append(dates, period_to_date[[per]])
}
```
indy_wells_plots is a hash of all the plots of groundwater of individual wells.
```{r}
#plotting an individual well's groundwater levels against time
library(ggplot2)
eer1 <- datt[,3]
df <- data.frame(dates, eer1)
ggplot(df, aes(dates, eer1))+geom_point()+theme(axis.text.x = element_text(angle = 60, hjust = 1))

#plotting each individual well's groundwater levels against time
indy_wells_plots <- hash()
for (colnum in seq(3, ncol(datt), 1)){
  groundwater_level <- datt[,colnum]
  df <- data.frame(dates, groundwater_level)
  p <- ggplot(df, aes(dates, groundwater_level))+geom_point()+theme(axis.text.x = element_text(angle = 60, hjust = 1))
  indy_wells_plots[[colnames(datt)[colnum]]] <- p
}
```
```{r}
library("cowplot")
#plotting sagehen discharge...
#as covariates (taken from MARSS50.Rmd calculations)
avg_discharge <- c(12.700000, 5.980000,3.480000,2.290000,1.945000,1.610000,1.595000, 1.610000,1.660000, 1.950000,2.160000,58.750000,52.350000,12.733333,4.890000,3.420000,2.490000,2.197500,3.000000,2.920000, 2.853333)
df <- data.frame(dates, avg_discharge)
discrete_discharge_plot <-   p <- ggplot(df, aes(dates, avg_discharge))+geom_point()+theme(axis.text.x = element_text(angle = 60, hjust = 1))
discrete_discharge_plot

#average discharge and an individual well in the same plot:
g <- ggplot(df, aes(dates))
g <- g + geom_point(aes(y=eer1, color="red"))
g <- g + geom_point(aes(y=avg_discharge, color="green"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
g <- g + scale_color_identity(name = "level",
                          breaks = c("red", "green"),
                          labels = c("EER1 groundwater level", "Sagehen average discharge"),
                          guide = "legend")
g

```
```{r}
#discharge measured from USGS:
remotes::install_github("hrbrmstr/albersusa")  #requires 'remotes' to be installed
library(albersusa); library(rgdal); library(sp)
us <- usa_composite(proj = "aeqd") 
library(forecast); library(imputeTS) 
library(dataRetrieval)
dailyDataAvailable <- whatNWISdata(siteNumber ="10343500") 
dailyDataAvailable
sagenum <- "10343500"
dailyDataAvailable <- whatNWISdata(siteNumber = sagenum,
                    parameterCd="00060",service="dv", statCd="00003")
parameterCd <- "00060"
startDate <- "2016-05-31"
endDate <- "2019-10-21"
discharge <- readNWISdv(sagenum, 
                    parameterCd, startDate, endDate)
sagehen_discharge <- discharge[, 3:4] %>%
  rename(timestamp = Date, Flow = X_00060_00003)
sagehen_discharge

many_dates <- sagehen_discharge$timestamp
flow <- sagehen_discharge$Flow
df <- data.frame(many_dates, flow)
discharge_plot<-ggplot(df, aes(many_dates, flow))+geom_point()+theme(axis.text.x = element_text(angle = 60, hjust = 1))+xlab("date") + ylab("flow") + scale_x_date(date_breaks = "1 year", date_labels =  "%Y")
```


```{r}
#eer1 groundwater levels, binned and averaged flow, and USGS measured flow all on one plot:
#first, must make the first two the correct length, with many NAs.
eer1_sparse <- rep(NA, length(many_dates))
eer1_hash <- hash(dates, eer1)
for (i in seq(1, length(many_dates), 1)){
  j <- as.character(many_dates[i])
  if (has.key(j, eer1_hash)){
    eer1_sparse[i] <- eer1_hash[[j]]
  }
}
#binned and averaged flow:
avg_flow_sparse <- rep(NA, length(many_dates))
avg_flow_hash <- hash(dates, avg_discharge)
for (i in seq(1, length(many_dates), 1)){
  j <- as.character(many_dates[i])
  if (has.key(j, avg_flow_hash)){
    avg_flow_sparse[i] <- avg_flow_hash[[j]]
  }
}

#one plot with eer1 groundwater, binned and avged discharge, and USGS measured sagehen discharge:
df <- data.frame(many_dates, avg_flow_sparse)
g <- ggplot(df, aes(many_dates))
g <- g + geom_point(aes(y=eer1_sparse, color="red"))
g <- g + geom_point(aes(y=flow, color="blue"))
g <- g + geom_point(aes(y=avg_flow_sparse, color="green"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
g <- g + scale_color_identity(name = "level",
                          breaks = c("red", "blue", "green"),
                          labels = c("EER1 groundwater level", "USGS measured discharge", "binned and averaged discharge"),
                          guide = "legend")
g <- g + xlab("date") + ylab("groundwater or flow") + scale_x_date(date_breaks = "1 month", date_labels =  "%b %Y") 

```

```{r}
#apply function rather than for loop:
plot_data_column = function (colnum) {
  groundwater_level <- datt[, colnum]
  well_sparse <- rep(NA, length(many_dates))
  well_hash <- hash(dates, groundwater_level)
  for (i in seq(1, length(many_dates), 1)){
    j <- as.character(many_dates[i])
    if (has.key(j, well_hash)){
      well_sparse[i] <- well_hash[[j]]
    }
  }
  df <- data.frame(many_dates, avg_flow_sparse)
  g <- ggplot(df, aes(many_dates))
  g <- g + geom_point(aes(y=well_sparse, color="red"))
  g <- g + geom_point(aes(y=flow, color="blue"))
  g <- g + geom_point(aes(y=avg_flow_sparse, color="green"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
  g <- g + scale_color_identity(name = "level",
                            breaks = c("red", "blue", "green"),
                            labels = c(colnum, "USGS measured discharge", "binned and averaged discharge"),
                            guide = "legend")
  g <- g + xlab("date") + ylab("groundwater or flow") + scale_x_date(date_breaks = "2 month", date_labels =  "%b %Y")
  g
}

myplots <- lapply(colnames(datt)[3:50], plot_data_column)
```


```{r}
#now, to average kiln and east meadows together as two groups:
east_wells <- data.frame(datt[, substring(colnames(datt), 1, 1) == "E"])
east_wells$mean_groundwater <- rowMeans(east_wells, na.rm = TRUE)
east_wells
kiln_wells <- data.frame(datt[, substring(colnames(datt), 1, 1) == "K"])
kiln_wells$mean_groundwater <- rowMeans(kiln_wells, na.rm = TRUE)
kiln_wells
#Add them to the hash, well_plots:
groundwater_level <- east_wells$mean_groundwater
well_spars <- rep(NA, length(many_dates)) ###THIS LINE MESSES WITH THE OTHER VALUES!
well_has <- hash(dates, groundwater_level)
for (i in seq(1, length(many_dates), 1)){
  j <- as.character(many_dates[i])
  if (has.key(j, well_has)){
    well_spars[i] <- well_has[[j]]
  }
}
#above this point, somehow wells_plots is changed!
df <- data.frame(many_dates, avg_flow_sparse)
g <- ggplot(df, aes(many_dates))
g <- g + geom_point(aes(y=well_spars, color="red"))
g <- g + geom_point(aes(y=flow, color="blue"))
g <- g + geom_point(aes(y=avg_flow_sparse, color="green"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
g <- g + scale_color_identity(name = "level",
                          breaks = c("red", "blue", "green"),
                          labels = c("east wells avg groundwater", "USGS measured discharge", "binned and averaged discharge"),
                          guide = "legend")
g <- g + xlab("date") + ylab("groundwater or flow") + scale_x_date(date_breaks = "2 month", date_labels =  "%b %Y")
myplots <- append(myplots, list(g))

oo <- kiln_wells$mean_groundwater
well_spar <- rep(NA, length(many_dates))
well_ha <- hash(dates, oo)
for (i in seq(1, length(many_dates), 1)){
  j <- as.character(many_dates[i])
  if (has.key(j, well_ha)){
    well_spar[i] <- well_ha[[j]]
  }
}
df <- data.frame(many_dates, avg_flow_sparse)
p <- ggplot(df, aes(many_dates))
p <- p + geom_point(aes(y=well_spar, color="red"))
p <- p + geom_point(aes(y=flow, color="blue"))
p <- p + geom_point(aes(y=avg_flow_sparse, color="green"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
p <- p + scale_color_identity(name = "level",
                          breaks = c("red", "blue", "green"),
                          labels = c("kiln wells avg groundwater", "USGS measured discharge", "binned and averaged discharge"),
                          guide = "legend")
p <- p + xlab("date") + ylab("groundwater or flow") + scale_x_date(date_breaks = "2 month", date_labels =  "%b %Y")
myplots <- append(myplots, list(p))

```
```{r}
#exporting multiple plots:
pdf(file="multiple_plots2.pdf")
par(mfrow=(c(2,3)))
myplots
dev.off()
```
```{r}
#exporting discharge plot
pdf(file="sagehen_discharge_plot.pdf")
discharge_plot
dev.off()
```
```{r}
#plotting each individual well with 2019 and 2018 on top of eachother:
#test: just for eer1:
dates_18<- dates[1:11]     #dates in 2018
dates_19 <- dates[12:21]    #dates in 2019
#changing dates_19 so they look like they are in the same year as 2018
for (i in seq(1, length(dates_19), 1)){
  dates_19[i] <- substr(dates_19[i],6,10)
}
for (i in seq(1, length(dates_18), 1)){
  dates_18[i] <- substr(dates_18[i],6,10)
}
eer1_18 <- eer1[1:11]       #obs in 2018
eer1_19 <- eer1[12:21]      #obs in 2019
df_18 <- data.frame(dates_18, eer1_18)
df_19 <- data.frame(dates_19, eer1_19)

ggplot() +
  geom_point(data=df_18, aes(x=dates_18,y=eer1_18,color="red"))+
  geom_point(data=df_19, aes(x=dates_19,y=eer1_19,color="blue"))+
  scale_color_identity(name = "level",
                          breaks = c("red", "blue"),
                          labels = c("2018", "2019"),
                          guide = "legend")+ 
  xlab("date") + ylab("groundwater level") + theme(axis.text.x = element_text(angle = 60, hjust = 1))
  
```
```{r}
#plotting each individual well with 2019 and 2018 on top of eachother:
plot_to_column = function (colnum) {
  groundwater_level <- datt[, colnum]
  levels_18 <- groundwater_level[1:11]       #obs in 2018
  levels_19 <- groundwater_level[12:21]      #obs in 2019
  df_18 <- data.frame(dates_18, levels_18)
  df_19 <- data.frame(dates_19, levels_19)
  
  ggplot() +
    geom_point(data=df_18, aes(x=dates_18,y=levels_18,color="red"))+
    geom_point(data=df_19, aes(x=dates_19,y=levels_19,color="blue"))+
    scale_color_identity(name = "level",
                            breaks = c("red", "blue"),
                            labels = c("2018", "2019"),
                            guide = "legend")+ 
    xlab("date") + ylab(paste(colnum,"groundwater level"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
}

overlayed_plots <- lapply(colnames(datt)[3:50], plot_to_column)
```
```{r}
#adding mean east and kiln
groundwater_level <- kiln_wells$mean_groundwater
  levels_18 <- groundwater_level[1:11]       #obs in 2018
  levels_19 <- groundwater_level[12:21]      #obs in 2019
  df_18 <- data.frame(dates_18, levels_18)
  df_19 <- data.frame(dates_19, levels_19)
  
  g <- ggplot() +
    geom_point(data=df_18, aes(x=dates_18,y=levels_18,color="red"))+
    geom_point(data=df_19, aes(x=dates_19,y=levels_19,color="blue"))+
    scale_color_identity(name = "level",
                            breaks = c("red", "blue"),
                            labels = c("2018", "2019"),
                            guide = "legend")+ 
    xlab("date") + ylab("mean kiln wells groundwater level")+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
  groundwater_level <- east_wells$mean_groundwater
  levels_18 <- groundwater_level[1:11]       #obs in 2018
  levels_19 <- groundwater_level[12:21]      #obs in 2019
  df_18 <- data.frame(dates_18, levels_18)
  df_19 <- data.frame(dates_19, levels_19)
  
  p <- ggplot() +
    geom_point(data=df_18, aes(x=dates_18,y=levels_18,color="red"))+
    geom_point(data=df_19, aes(x=dates_19,y=levels_19,color="blue"))+
    scale_color_identity(name = "level",
                            breaks = c("red", "blue"),
                            labels = c("2018", "2019"),
                            guide = "legend")+ 
    xlab("date") + ylab("mean east wells groundwater level")+ theme(axis.text.x = element_text(angle = 60, hjust = 1))
  overlayed_plots <- append(overlayed_plots, list(p))
    overlayed_plots <- append(overlayed_plots, list(g))
```
```{r}
#exporting overlayed plots
pdf(file="overlayed_gw_plots.pdf")
overlayed_plots
dev.off()
```




