---
title: "ground water MARSS with lagged covariates"
author: "Julia Nicholson"
date: "01/07/21"
output: html_document
---

```{r setup, include=FALSE}
#Same process as Lab7, but increasing number of wells we allow:

library(MARSS)
library(tidyverse)
library(gridExtra)
dat <- as.matrix(read.csv("C:/Users/Hugh/Desktop/Riverlab/gw_by_obs_period.csv"), stringsAsFactors=FALSE, header=FALSE)

#don't want to zscone bi_week_fac
observation_periods <- dat[,2]
transformed_dat <- zscore(dat)


transformed_dat[,2] <- observation_periods
dat_50 <- transformed_dat[,(colSums(is.na(dat)) < 10)]
groundwater_variates <- t(dat_50[,3:29])
```
```{r}
# covariates are sagehen creek discharge.
#install.packages(c('rgdal','sp','forecast','imputeTS','dataRetrieval'))
#install.packages('remotes')
remotes::install_github("hrbrmstr/albersusa")  #requires 'remotes' to be installed
#1-Maps
library(albersusa); library(rgdal); library(sp)

us <- usa_composite(proj = "aeqd") 
library(forecast); library(imputeTS) 
#3-US National Water Information System
library(dataRetrieval)
sagehenINFO <- readNWISsite("10343500")
sagehenINFO

dailyDataAvailable <- whatNWISdata(siteNumber ="10343500") 
dailyDataAvailable

sagenum <- "10343500"

#choice of discharge time-series, daily values ("dv") and only mean values ("00003")
dailyDataAvailable <- whatNWISdata(siteNumber = sagenum,
                    parameterCd="00060",service="dv", statCd="00003")
dailyDataAvailable

parameterCd <- "00060"
#Specify a time frame 
startDate <- "2018-01-31"
endDate <- "2019-10-21"

#Download the data
discharge <- readNWISdv(sagenum, 
                    parameterCd, startDate, endDate)
sagehen_discharge <- discharge[, 3:4] %>%
  rename(timestamp = Date, Flow = X_00060_00003)
  
#Bin discharge data into bi_weeks for averaging:
observation_df <- data.frame(matrix(NA, nrow = 39, ncol = 0))
observation_df["timestamp"] <- as.Date(c("2018-05-30","2018-05-31",
                                 "2018-06-17", "2018-06-18",
                                 "2018-06-29", "2018-06-30",
                                 "2018-07-15", "2018-07-16",
                                 "2018-07-24", "2018-07-26",
                                 "2018-08-09",
                                 "2018-08-23", "2018-08-24",
                                 "2018-09-15",
                                 "2018-09-28", "2018-09-29",
                                 "2018-10-13",
                                 "2018-11-17",
                                 "2019-06-01", "2019-06-02",
                                 "2019-06-16", "2019-06-17",
                                 "2019-07-04", "2019-07-05", "2019-07-06",
                                 "2019-07-25",
                                 "2019-08-03", "2019-08-04", "2019-08-05",
                                 "2019-08-19",
                                 "2019-09-01", "2019-09-03", "2019-09-04", "2019-09-02",
                                 "2019-09-20",
                                 "2019-10-04",
                                 "2019-10-18", "2019-10-20", "2019-10-19"))
observation_df["observation_period"] <- as.factor(c(1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 7, 8, 9, 9, 10, 11, 12, 12, 13, 13, 14, 14, 14, 15, 16, 16, 16, 17, 18, 18, 18, 18, 19, 20, 21, 21, 21))

test_new <- left_join(sagehen_discharge, observation_df, by = "timestamp")
discharge_by_obs_period <- test_new[!is.na(test_new$observation_period),]
test_2 <- discharge_by_obs_period %>% 
  group_by(observation_period) %>%
  summarize(mean_flow = mean(Flow))
discharge_by_obs_period <- data.frame(test_2)

discharge_covariates <- discharge_by_obs_period$mean_flow
discharge_covariates_unZd <-discharge_covariates
discharge_covariates <- zscore(discharge_covariates)

#now to create different observation data.frames for covariate discharges of lags: 1 week, 2 week, 3 week, 4 week, and 2 months:
odl1 <- observation_df
odl1["timestamp"] <- observation_df$timestamp - 7
odl2 <- observation_df
odl2["timestamp"] <- observation_df$timestamp - 14
odl3 <- observation_df
odl3["timestamp"] <- observation_df$timestamp - 21
odl4 <- observation_df
odl4["timestamp"] <- observation_df$timestamp - 28
odl5 <- observation_df
odl5["timestamp"] <- observation_df$timestamp - 35
odl_1.5mo <- observation_df
odl_1.5mo["timestamp"] <- observation_df$timestamp - 45
odl7 <- observation_df
odl7["timestamp"] <- observation_df$timestamp - 52
odl_2mo <- observation_df
odl_2mo["timestamp"] <- observation_df$timestamp - 60
odl9 <- observation_df
odl9["timestamp"] <- observation_df$timestamp - 67
odl_2.5mo <- observation_df
odl_2.5mo["timestamp"] <- observation_df$timestamp - 75
odl11 <- observation_df
odl11["timestamp"] <- observation_df$timestamp - 82
odl_3mo <- observation_df
odl_3mo["timestamp"] <- observation_df$timestamp - 90

lagged_ods <- list(odl1, odl2, odl3, odl4, odl5, odl_1.5mo, odl7, odl_2mo, odl9, odl_2.5mo, odl11, odl_3mo)
different_covariates <- list()
diff_covariates_unZd <- list(discharge_covariates_unZd)#a list of the covariates without hte zscore, for plotting later
for (i in seq(1, length(lagged_ods), 1)){
  od <- lagged_ods[[i]]
  test_new <- left_join(sagehen_discharge, od, by = "timestamp")
  discharge_by_obs_period <- test_new[!is.na(test_new$observation_period),]
  test_2 <- discharge_by_obs_period %>% 
    group_by(observation_period) %>%
    summarize(mean_flow = mean(Flow))
  discharge_by_obs_period <- data.frame(test_2)
  
  d_covariates <- discharge_by_obs_period$mean_flow
  diff_covariates_unZd<-append(diff_covariates_unZd, list(d_covariates))
  d_covariates <- zscore(d_covariates)
  different_covariates <- append(different_covariates, list(d_covariates))
}

```


```{r}
#Model specification: MAR:
#Hypothesis 1: Each well responds uniquely
C_1 = "unequal"
#Hypothesis 5: Every well is part of a universal state
C_5 = "equal"
#Hypothesis 6: Kiln and East restrict C
C_6 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  meadow <- substring(wellname, 1, 1)
  C_6 <- rbind(C_6, c(meadow))
}

#Hypothesis 8: HGMZ restrict C
C_8 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  HGMZ <- substring(wellname, 3, 3)
  C_8 <- rbind(C_8, c(HGMZ))
}
#Hypothesis 8.5 : HGMZ restrict C, only fan and terrace are counted together.
C_8.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  HGMZ <- substring(wellname, 3, 3)
  if (HGMZ == "F" | HGMZ == "T") {
    C_8.5 <- rbind(C_8.5, c("Fan or Terrace"))
  } else if (HGMZ == "R"){
    C_8.5 <- rbind(C_8.5, c("riparian"))
  }
}
#Hypothesis 9: plant functional type affecting C matrix:
C_9 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  plant <- substring(wellname, 2, 2)
  C_9 <- rbind(C_9, c(plant))
}

#Hypothesis 10: plant/HGMZ pair:
C_10 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  plant <- substring(wellname, 2, 2)
  HGMZ <- substring(wellname, 3, 3)
  C_10 <- rbind(C_10, c(paste(plant, HGMZ)))
}

characteristics <- as.matrix(read.csv("C:/Users/Hugh/Desktop/Riverlab/sagehen_meadows/data/field_observations/groundwater/Wells_Characteristics.csv"), stringsAsFactors=FALSE, header=FALSE)
characteristics <- characteristics[!is.na(characteristics[,2]) & characteristics[,2]==" 1",]
characteristics[,1] <- gsub("-", ".",characteristics[,1])
###FIMXME: not zscored, because of the 10000 entry.

#A dictionary for TWI of each well:
library(hash)
TWIs <- hash()
for (rindex in 1:nrow(characteristics)){
  TWIs[[characteristics[rindex, 1]]] <- characteristics[rindex, 7]
}

#Hypothesis 11: C effected by TWI of the well:
C_11 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  TWI <- as.numeric(TWIs[[wellname]])
  bin <- 0
  if (is.null(TWIs[[wellname]])){
    bin <- 1
    ###FIXME: some of the TWIs are not calculated, so I had to put in this case!
  } else if (TWI < 2){
    bin <- 1
  } else if (TWI < 3){
    bin <- 2
  } else if (TWI < 4){
    bin <- 3
  } else if (TWI < 5){
    bin <- 4
  } else if (TWI < 6){
    bin <- 5
  } else if (TWI < 7){
    bin <- 6
  } else if (TWI < 20){
    bin <- 7
  } else if (TWI == 1000.0000000){
    bin <- 8
  }
  C_11 <- rbind(C_11, c(bin))
}

#Hypothesis 11.5: C effected by TWI of the well, grouped with fewer groups:
C_11.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  TWI <- as.numeric(TWIs[[wellname]])
  bin <- 0
  if (is.null(TWIs[[wellname]])){
    bin <- 1
    ###FIXME: some of the TWIs are not calculated, so I had to put in this case!
  } else if (TWI < 2){
    bin <- 1
  } else if (TWI < 4){
    bin <- 2
  } else if (TWI < 7){
    bin <- 3
  } else if (TWI < 20){
    bin <- 4
  } else if (TWI == 1000.0000000){
    bin <- 5
  }
  C_11.5 <- rbind(C_11.5, c(bin))
}
#C matrix restricted according to binned distance from main channel:
characteristics[,3] <- zscore(as.numeric(characteristics[,3]))
mean_main <- mean(as.numeric(characteristics[,3]))
#A dictionary for TWI of each well:
dist_to_mains <- hash()
for (rindex in 1:nrow(characteristics)){
  dist_to_mains[[characteristics[rindex, 1]]] <- characteristics[rindex, 3]
}

#Hypothesis 12: C effected by distance to main chanel of the well:
C_12 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  distance <- as.numeric(dist_to_mains[[wellname]])
  bin <- 0
  if (is.null(dist_to_mains[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 2
  } else if (distance < 0){
    bin <- 3
  } else if (distance < .5){
    bin <- 4
  } else if (distance < 1){
    bin <- 5
  } else {
    bin <- 6
  }
  C_12 <- rbind(C_12, c(bin))
}

#Hypothesis 12.5: C effected by distance to main chanel of the well, but with 4 groups:
C_12.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  distance <- as.numeric(dist_to_mains[[wellname]])
  bin <- 0
  if (is.null(dist_to_mains[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 1
  } else if (distance < .5){
    bin <- 2
  } else {
    bin <- 3
  }
  C_12.5 <- rbind(C_12.5, c(bin))
}
#C matrix restricted according to binned distance from nearest channel:
characteristics[,4] <- zscore(as.numeric(characteristics[,4]))
mean_near <- mean(as.numeric(characteristics[,4]))
#A dictionary for TWI of each well:
dist_to_nears <- hash()
for (rindex in 1:nrow(characteristics)){
  dist_to_nears[[characteristics[rindex, 1]]] <- characteristics[rindex, 4]
}

#Hypothesis 13: C effected by distance to nearest chanel:
C_13 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  distance <- as.numeric(dist_to_nears[[wellname]])
  bin <- 0
  if (is.null(dist_to_nears[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 2
  } else if (distance < 0){
    bin <- 3
  } else if (distance < .5){
    bin <- 4
  } else if (distance < 1){
    bin <- 5
  } else {
    bin <- 6
  }
  C_13 <- rbind(C_13, c(bin))
}

#Hypothesis 13.5: C effected by distance to nearest chanel, but with 3 groups rather than 6:
C_13.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  distance <- as.numeric(dist_to_nears[[wellname]])
  bin <- 0
  if (is.null(dist_to_nears[[wellname]])){
    bin <- 2
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 1
  } else if (distance < .5){
    bin <- 2
  } else {
    bin <- 3
  }
  C_13.5 <- rbind(C_13.5, c(bin))
}

C_11[,1] <- as.character(C_11[,1])
C_11.5[,1] <- as.character(C_11.5[,1])
C_12[,1] <- as.character(C_12[,1])
C_12.5[,1] <- as.character(C_12.5[,1])
C_13[,1] <- as.character(C_13[,1])
C_13.5[,1] <- as.character(C_13.5[,1])

#Hypothesis 14: Meadow AND HGMZ:
C_14 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates)){
  meadow <- substring(wellname, 1, 1)
  HGMZ <- substring(wellname, 3, 3)
  C_14 <- rbind(C_14, c(paste(meadow, HGMZ)))
}

```


```{r}
#djdkdk
R. <- "zero"
#Assuming no overall trend in data:
U. <- "zero"
#assuming wells do not interact with oneanother, and no density dependence, since we zscored.
B. <- "identity"
#Assuming equal process error 
Q. <- "diagonal and unequal"
A. <- "zero"
#discharge_covariates uploaded and manipulated in chunk 2.
#each different c. is a different set of discharge covariates, with a lag of 0, 1, 2, 3, 4 weeks or 2 months.
c. <- matrix(discharge_covariates, nrow = 1) 
c.1 <- matrix(different_covariates[[1]], nrow =1)
c.2 <- matrix(different_covariates[[2]], nrow =1)
c.3 <- matrix(different_covariates[[3]], nrow =1)
c.4 <- matrix(different_covariates[[4]], nrow =1)
c.5 <- matrix(different_covariates[[5]], nrow =1)
c.1.5mo <- matrix(different_covariates[[6]], nrow =1)
c.7 <- matrix(different_covariates[[7]], nrow =1)
c.2mo <- matrix(different_covariates[[8]], nrow =1)
c.9 <- matrix(different_covariates[[9]], nrow =1)
c.2.5mo <- matrix(different_covariates[[10]], nrow =1)
c.11 <- matrix(different_covariates[[11]], nrow =1)
c.3mo <- matrix(different_covariates[[12]], nrow =1)
Z. <- "identity"
```
```{r}
#Models:
#Hyp. #1: every well responds its own way
model_1 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_1, c=c.2mo, A= A., Q ="diagonal and unequal"), control=list(maxit=10000))
# AICc: 1002.745 Q diagonal and equal
#AICc: 680.4154 Q diagonal and unequal

#Hypothesis 5: Every well is part of a universal state
model_5 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_5, c=c.4, A= A., Q = "diagonal and equal"))
#AICc: 985.16 Q diagonal and equal
# AICc: 689.2232 Q diagonal and unequal

#Hypothesis 6: Kiln and East restrict C:
model_6 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_6, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 974.1982 Q diagonal and equal
# AICc: 668.8699 Q diagonal and unequal

#Hypothesis 8: HGMZ restrict C
model_8 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_8, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 983.8582 Q diag and equal
#AICc: 677.4209 Q d and unewual

#Hypothesis 8.5 : HGMZ restrict C, only fan and terrace are counted together.
model_8.5 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_8.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 985.6888 Q diag and equal
#AICc: 685.7831 Q diag and unequal

#Hypothesis 9: plant functional type affecting C matrix:
model_9 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_9, c=c., A= A., Q = "diagonal and equal"))
#AICc: 987.4882 Q diag and equal
#AICc: 682.6821 Q diag and unequal

#Hypothesis 10:
model_10 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_10, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 991.1521 Q diag and equal
#AICc: 680.9046 Q diag and unequal

#Hypothesis 11: TWIs, 6 groups
model_11 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_11, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 2879.543 d and e
#AICc: 2655.171 d an une

#Hypothesis 11.5: TWIs, 3 groups
model_11.5 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_11.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 2494.783
#AICc: 2374.343

#Hypothesis 12: C restricted by distance to main channel, with 6 bins
model_12 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_12, c=c., A= A., Q = "diagonal and unequal"))
#AICc: Q diag and unequal
#AICc: 2509.169

#Hypothesis 12.5: C restricted by distance to main channel, with 3 groups
model_12.5 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_12.5, c=c., A= A., Q = "diagonal and unequal"))
# AICc: 1927.666

#Hypothesis 13: C restricted by distance to nearest channel, with 6 bins
model_13 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_13, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 2574.755

#Hypothesis 13.5: C restricted by distance to nearest channel, with 3 bins
model_13.5 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_13.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 2016.163

#Hypothesis 14: Meadow U HGMZ
model_14 <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_14, c=c., A= A., Q = "diagonal and unequal"))
# AICc 664.5104Q d and uneq

```
```{r}
#construct a list of dataframes, one data frame for each set of covariates: c., c.1, ... c.2mo . Each data frame will have a column of model names and a column of the AICc that model got. 
lagged_dfs <- list()
diff_cs <- list(c., c.1, c.2, c.3, c.4, c.5, c.1.5mo, c.7, c.2mo, c.9, c.2.5mo, c.11, c.3mo)
diff_Cs <- list(C_1,C_5,C_6,C_8,C_8.5,C_9,C_10,C_11,C_11.5,C_12,C_12.5,C_13,C_13.5,C_14)
model_names <- c(1,5,6,8,8.5,9,10,11,11.5,12,12.5,13,13.5,14)
for (i in seq(1, length(diff_cs), 1)){
  c_mat <- diff_cs[[i]]
  df <- data.frame("model"=numeric(),"AICc"=numeric())
  for (j in seq(1, length(diff_Cs), 1)){
    C_mat <- diff_Cs[[j]]
    m <- MARSS(groundwater_variates, model = list(Z = Z., R = R., U=U., B=B., C=C_mat, c=c_mat, A= A., Q ="diagonal and unequal"), control=list(maxit=10000))
    df1 <- data.frame("model"=model_names[j], "AICc"=m$AICc)
    df <- rbind(df, df1)
  }
  lagged_dfs <- append(lagged_dfs, list(df))
}
```

create a list of plots; one for each lagged set of covariates. Each plot has the 14 hypotheses models on the x axis, and their AICc scores on the y axis.
```{r}
lagged_plots<-list()
mycolors<-c("#99FF00", "#FF0000", "#330066", "#0066CC", "#330033", "#FF3300", "#FFCC00", "#003300", "#CC00CC", "#999933", "#0033FF", "#00FFFF", "#66CC00", "#663300")
lags <- c(0,1,2,3,4,5,6,7,8,9,10,11,12)
for (i in seq(1, length(lagged_dfs),1)){
  k<-lagged_dfs[[i]]
  k$model <- as.factor(k$model)
  g<- ggplot(k, aes(as.factor(model_names), color=model))+geom_point(aes(y=AICc)) + xlab("model number")+ylab("AICc score")+scale_color_manual(name="Model",values=mycolors, labels=c("1: each well responds uniquely","5: universal state","6: meadow","8: HGMZ","8.5: HGMZ; fan and terrace together","9: PFT","10: PFT and HGMZ","11: TWI, 6 bins","11.5: TWI, 3 bins","12: distance to main channel, 6 bins","12.5:distance to main channel, 3 bins","13:distance to nearest channel, 6 bins","13.5: distance to nearest channel, 3 bins","14: meadow and HGMZ"))+ggtitle(paste("Covariate Discharge with a lag of ",as.character(lags[[i]])," weeks"))
  lagged_plots<-append(lagged_plots, list(g))
}
```
```{r}
#saving plots
pdf(file="lagged_covariates_plots_50.pdf")
lagged_plots
dev.off()
```


```{r}
###    75% completeness    ####
dat_75 <- transformed_dat[,(colSums(is.na(dat)) < 5)]

###TEST: DOES LOG TRANSFORM HELP?
#dat_75 <- log10(dat_75)
groundwater_variates_75 <- t(dat_75[,3:21])
#groundwater_variates_75 <- log(groundwater_variates_75 + 5)
```


```{r}
#Model specification: MAR:
#Hypothesis 1: Each well responds uniquely
C_1 = "unequal"
#Hypothesis 5: Every well is part of a universal state
C_5 = "equal"
#Hypothesis 6: Kiln and East restrict C
C_6 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  meadow <- substring(wellname, 1, 1)
  C_6 <- rbind(C_6, c(meadow))
}

#Hypothesis 8: HGMZ restrict C
C_8 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  HGMZ <- substring(wellname, 3, 3)
  C_8 <- rbind(C_8, c(HGMZ))
}
#Hypothesis 8.5 : HGMZ restrict C, only fan and terrace are counted together.
C_8.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  HGMZ <- substring(wellname, 3, 3)
  if (HGMZ == "F" | HGMZ == "T") {
    C_8.5 <- rbind(C_8.5, c("Fan or Terrace"))
  } else if (HGMZ == "R"){
    C_8.5 <- rbind(C_8.5, c("riparian"))
  }
}
#Hypothesis 9: plant functional type affecting C matrix:
C_9 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  plant <- substring(wellname, 2, 2)
  C_9 <- rbind(C_9, c(plant))
}

#Hypothesis 10: plant/HGMZ pair:
C_10 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  plant <- substring(wellname, 2, 2)
  HGMZ <- substring(wellname, 3, 3)
  C_10 <- rbind(C_10, c(paste(plant, HGMZ)))
}

characteristics <- as.matrix(read.csv("C:/Users/Hugh/Desktop/Riverlab/sagehen_meadows/data/field_observations/groundwater/Wells_Characteristics.csv"), stringsAsFactors=FALSE, header=FALSE)
characteristics <- characteristics[!is.na(characteristics[,2]) & characteristics[,2]==" 1",]
characteristics[,1] <- gsub("-", ".",characteristics[,1])
###FIMXME: not zscored, because of the 10000 entry.

#A dictionary for TWI of each well:
library(hash)
TWIs <- hash()
for (rindex in 1:nrow(characteristics)){
  TWIs[[characteristics[rindex, 1]]] <- characteristics[rindex, 7]
}

#Hypothesis 11: C effected by TWI of the well:
C_11 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  TWI <- as.numeric(TWIs[[wellname]])
  bin <- 0
  if (is.null(TWIs[[wellname]])){
    bin <- 1
    ###FIXME: some of the TWIs are not calculated, so I had to put in this case!
  } else if (TWI < 2){
    bin <- 1
  } else if (TWI < 3){
    bin <- 2
  } else if (TWI < 4){
    bin <- 3
  } else if (TWI < 5){
    bin <- 4
  } else if (TWI < 6){
    bin <- 5
  } else if (TWI < 7){
    bin <- 6
  } else if (TWI < 20){
    bin <- 7
  } else if (TWI == 1000.0000000){
    bin <- 8
  }
  C_11 <- rbind(C_11, c(bin))
}

#Hypothesis 11.5: C effected by TWI of the well, grouped with fewer groups:
C_11.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  TWI <- as.numeric(TWIs[[wellname]])
  bin <- 0
  if (is.null(TWIs[[wellname]])){
    bin <- 1
    ###FIXME: some of the TWIs are not calculated, so I had to put in this case!
  } else if (TWI < 2){
    bin <- 1
  } else if (TWI < 4){
    bin <- 2
  } else if (TWI < 7){
    bin <- 3
  } else if (TWI < 20){
    bin <- 4
  } else if (TWI == 1000.0000000){
    bin <- 5
  }
  C_11.5 <- rbind(C_11.5, c(bin))
}
#C matrix restricted according to binned distance from main channel:
characteristics[,3] <- zscore(as.numeric(characteristics[,3]))
mean_main <- mean(as.numeric(characteristics[,3]))
#A dictionary for TWI of each well:
dist_to_mains <- hash()
for (rindex in 1:nrow(characteristics)){
  dist_to_mains[[characteristics[rindex, 1]]] <- characteristics[rindex, 3]
}

#Hypothesis 12: C effected by distance to main chanel of the well:
C_12 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_mains[[wellname]])
  bin <- 0
  if (is.null(dist_to_mains[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 2
  } else if (distance < 0){
    bin <- 3
  } else if (distance < .5){
    bin <- 4
  } else if (distance < 1){
    bin <- 5
  } else {
    bin <- 6
  }
  C_12 <- rbind(C_12, c(bin))
}

#Hypothesis 12.5: C effected by distance to main chanel of the well, but with 4 groups:
C_12.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_mains[[wellname]])
  bin <- 0
  if (is.null(dist_to_mains[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 1
  } else if (distance < .5){
    bin <- 2
  } else {
    bin <- 3
  }
  C_12.5 <- rbind(C_12.5, c(bin))
}
#C matrix restricted according to binned distance from nearest channel:
characteristics[,4] <- zscore(as.numeric(characteristics[,4]))
mean_near <- mean(as.numeric(characteristics[,4]))
#A dictionary for TWI of each well:
dist_to_nears <- hash()
for (rindex in 1:nrow(characteristics)){
  dist_to_nears[[characteristics[rindex, 1]]] <- characteristics[rindex, 4]
}

#Hypothesis 13: C effected by distance to nearest chanel:
C_13 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_nears[[wellname]])
  bin <- 0
  if (is.null(dist_to_nears[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 2
  } else if (distance < 0){
    bin <- 3
  } else if (distance < .5){
    bin <- 4
  } else if (distance < 1){
    bin <- 5
  } else {
    bin <- 6
  }
  C_13 <- rbind(C_13, c(bin))
}

#Hypothesis 13.5: C effected by distance to nearest chanel, but with 3 groups rather than 6:
C_13.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_nears[[wellname]])
  bin <- 0
  if (is.null(dist_to_nears[[wellname]])){
    bin <- 2
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 1
  } else if (distance < .5){
    bin <- 2
  } else {
    bin <- 3
  }
  C_13.5 <- rbind(C_13.5, c(bin))
}

#Hypothesis 14: Meadow AND HGMZ:
C_14 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  meadow <- substring(wellname, 1, 1)
  HGMZ <- substring(wellname, 3, 3)
  C_14 <- rbind(C_14, c(paste(meadow, HGMZ)))
}

C_11[,1] <- as.character(C_11[,1])
C_11.5[,1] <- as.character(C_11.5[,1])
C_12[,1] <- as.character(C_12[,1])
C_12.5[,1] <- as.character(C_12.5[,1])
C_13[,1] <- as.character(C_13[,1])
C_13.5[,1] <- as.character(C_13.5[,1])
```

```{r}
#for 75%completeness
#construct a list of dataframes, one data frame for each set of covariates: c., c.1, ... c.2mo . Each data frame will have a column of model names and a column of the AICc that model got. 
lagged_dfs_75 <- list()
diff_cs <- list(c., c.1, c.2, c.3, c.4, c.5, c.1.5mo, c.7, c.2mo, c.9, c.2.5mo, c.11, c.3mo)
diff_Cs <- list(C_1,C_5,C_6,C_8,C_8.5,C_9,C_10,C_11,C_11.5,C_12,C_12.5,C_13,C_13.5,C_14)
model_names <- c(1,5,6,8,8.5,9,10,11,11.5,12,12.5,13,13.5,14)
for (i in seq(1, length(diff_cs), 1)){
  c_mat <- diff_cs[[i]]
  df <- data.frame("model"=numeric(),"AICc"=numeric())
  for (j in seq(1, length(diff_Cs), 1)){
    C_mat <- diff_Cs[[j]]
    m <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_mat, c=c_mat, A= A., Q ="diagonal and unequal"), control=list(maxit=10000))
    df1 <- data.frame("model"=model_names[j], "AICc"=m$AICc)
    df <- rbind(df, df1)
  }
  lagged_dfs_75 <- append(lagged_dfs_75, list(df))
}
```
```{r}
#a list of plots for the 75%completeness wells
lagged_plots_75<-list()
mycolors<-c("#99FF00", "#FF0000", "#330066", "#0066CC", "#330033", "#FF3300", "#FFCC00", "#003300", "#CC00CC", "#999933", "#0033FF", "#00FFFF", "#66CC00", "#663300")
lags <- c(0,1,2,3,4,5,6,7,8,9,10,11,12)
for (i in seq(1, length(lagged_dfs_75),1)){
  k<-lagged_dfs_75[[i]]
  k$model <- as.factor(k$model)
  g<- ggplot(k, aes(as.factor(model_names), color=model))+geom_point(aes(y=AICc)) + xlab("model number")+ylab("AICc score")+scale_color_manual(name="Model",values=mycolors, labels=c("1: indiviudal\n    well","5: universal\n   state","6: meadow","8: HGMZ","8.5: HGMZ, fan\n and terrace as one","9: PFT","10: PFT and HGMZ","11: TWI, 6 bins","11.5: TWI, 3 bins","12: Distance to\n main channel, 6 bins","12.5: Distance to\n main channel, 3 bins","13: Distance to\n nearest channel,\n 6 bins","13.5: Distance to\n nearest channel, 3 bins","14: meadow + HGMZ"))+ggtitle(paste("Covariate Discharge with a lag of ",as.character(lags[[i]])," weeks"))
  lagged_plots_75<-append(lagged_plots_75, list(g))
}
```
store multiple plots in one file:
```{r}
#making a list of plots, one for each set of lagged covariates. Each plot will have 
library("ggpubr")
flow<-sagehen_discharge$Flow
many_dates<-sagehen_discharge$timestamp

all_ods <-append(list(observation_df), lagged_ods)
arranged_plots<-list()

for (lag in seq(1, length(all_ods),1)){
  observation_df1<-all_ods[[lag]]
  period_to_date <- hash()
  for (row in seq(1, nrow(observation_df1), 1)){
    per <- observation_df1[row, 2]
    date <- as.character(observation_df1[row, 1])
    period_to_date[per] <- date
  }
  dates <- c()
  for (per in seq(1,21,1)){
    dates <- append(dates, period_to_date[[as.character(per)]])
  }
  
  avg_flow_sparse <- rep(NA, length(many_dates))
  avg_flow_hash <- hash(dates, diff_covariates_unZd[[lag]])
  for (i in seq(1, length(many_dates), 1)){
    j <- as.character(many_dates[i])
    if (has.key(j, avg_flow_hash)){
      avg_flow_sparse[i] <- avg_flow_hash[[j]]
    }
  }
  g<-ggplot(sagehen_discharge,aes(many_dates))+geom_point(aes(y=flow,color="blue"))+geom_point(aes(y=avg_flow_sparse,color="green"))+ theme(axis.text.x = element_text(angle = 60, hjust = 1))+ scale_color_identity(name = "level",
                            breaks = c("blue", "green"),
                            labels = c("USGS measured discharge", "avg. discharge (covariates)"), guide = "legend") + xlab("date") + ylab("Flow") + scale_x_date(date_breaks = "1 month", date_labels =  "%b %Y")
  k<-lagged_plots_75[[lag]]
  t<-ggarrange(k,g,ncol=1)
  arranged_plots<-append(arranged_plots, list(t))
}

```
Save all of these plots to pdf:
```{r}
pdf(file="lagged_covariate_plots_75.pdf")
arranged_plots
dev.off()
```

```{r}
#Models for 75% completeness:
#Hyp. #1: every well responds its own way
model_1 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_1, c=c., A= A., Q ="diagonal and unequal"), control=list(maxit=10000))
# AICc: 770.5099Q diagonal and equal
#AICc: 469.2754 Q diagonal and unequal

#Hypothesis 5: Every well is part of a universal state
model_5 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 758.5467 Q diagonal and equal
#AICc: 483.5237 Q diagonal and unequal

#Hypothesis 6: Kiln and East restrict C:
model_6 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_6, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 749.2678 Q diagonal and equal
#AICc: 463.7356 Q diagonal and unequal

#Hypothesis 8: HGMZ restrict C
model_8 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_8, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 758.6903 Q diagonal and equal
#AICc: 473.3753 Q d and unewual

#Hypothesis 8.5 : HGMZ restrict C, only fan and terrace are counted together.
model_8.5 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_8.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 757.8197  Q diag and equal
#AICc: 478.5212 Q diag and unequal

#Hypothesis 9: plant functional type affecting C matrix:
model_9 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_9, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 764.061 Q diag and equal
#AICc: 480.8528 Q diag and unequal

#Hypothesis 10:
model_10 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_10, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 761.5927 Q diag and equal
#AICc: 476.4058 Q diag and unequal

#Hypothesis 11: TWI with 8 groups
model_11 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_11, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 2146.216
#AICc: 1959.838

#Hypothesis 11.5: TWI with 5 groups
model_11.5 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_11.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 1714.508 diag and equal
#AICc: 1545.89 diag and unequal

#Hypothesis 12: C restricted by distance to main channel, with 6 bins
model_12 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_12_test, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 1844.176  Q diag and equal
#AICc: 1676.011 Q diag and unequal

#Hypothesis 12.5: C restricted by distance to main channel, with 3 groups
model_12.5 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_12.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 1551.931 diagonal and equal
#AICc: 1435.415 diag and uneual

#Hypothesis 13: C restricted by distance to nearest channel, with 6 bins
model_13 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_13, c=c., A= A., Q = "diagonal and unequal"))
#AICc 1895.378 Q diag and equal
#AICc: 1720.203 Q diag and equal

#Hypothesis 13.5: C restricted by distance to nearest channel, with 3 bins
model_13.5 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_13.5, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 1592.24 d and equal
#AICc: 1526.689 d and unequal

#Hypothesis 14:combo of meadow and HGMZ
model_14 <- MARSS(groundwater_variates_75, model = list(Z = Z., R = R., U=U., B=B., C=C_14, c=c., A= A., Q = "diagonal and unequal"))
#AICc: 755.7961 d and equal
#AICc: 502.5736 d and unequal
```

Now, upload TWI data to use to affect C matrix:
```{r}
characteristics <- as.matrix(read.csv("C:/Users/Hugh/Desktop/Riverlab/sagehen_meadows/data/field_observations/groundwater/Wells_Characteristics.csv"), stringsAsFactors=FALSE, header=FALSE)
characteristics <- characteristics[!is.na(characteristics[,2]) & characteristics[,2]==" 1",]
characteristics[,1] <- gsub("-", ".",characteristics[,1])
###FIMXME: not zscored, because of the 10000 entry.

#A dictionary for TWI of each well:
library(hash)
TWIs <- hash()
for (rindex in 1:nrow(characteristics)){
  TWIs[[characteristics[rindex, 1]]] <- characteristics[rindex, 7]
}

#Hypothesis 11: C effected by TWI of the well:
C_11 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  TWI <- as.numeric(TWIs[[wellname]])
  bin <- 0
  if (is.null(TWIs[[wellname]])){
    bin <- 1
    ###FIXME: some of the TWIs are not calculated, so I had to put in this case!
  } else if (TWI < 2){
    bin <- 1
  } else if (TWI < 3){
    bin <- 2
  } else if (TWI < 4){
    bin <- 3
  } else if (TWI < 5){
    bin <- 4
  } else if (TWI < 6){
    bin <- 5
  } else if (TWI < 7){
    bin <- 6
  } else if (TWI < 20){
    bin <- 7
  } else if (TWI == 1000.0000000){
    bin <- 8
  }
  C_11 <- rbind(C_11, c(bin))
}

#Hypothesis 11.5: C effected by TWI of the well, grouped with fewer groups:
C_11.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  TWI <- as.numeric(TWIs[[wellname]])
  bin <- 0
  if (is.null(TWIs[[wellname]])){
    bin <- 1
    ###FIXME: some of the TWIs are not calculated, so I had to put in this case!
  } else if (TWI < 2){
    bin <- 1
  } else if (TWI < 4){
    bin <- 2
  } else if (TWI < 7){
    bin <- 3
  } else if (TWI < 20){
    bin <- 4
  } else if (TWI == 1000.0000000){
    bin <- 5
  }
  C_11.5 <- rbind(C_11.5, c(bin))
}
```


```{r}
#C matrix restricted according to binned distance from main channel:
characteristics[,3] <- zscore(as.numeric(characteristics[,3]))
mean_main <- mean(as.numeric(characteristics[,3]))
#A dictionary for TWI of each well:
dist_to_mains <- hash()
for (rindex in 1:nrow(characteristics)){
  dist_to_mains[[characteristics[rindex, 1]]] <- characteristics[rindex, 3]
}

#Hypothesis 12: C effected by distance to main chanel of the well:
C_12 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_mains[[wellname]])
  bin <- 0
  if (is.null(dist_to_mains[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 2
  } else if (distance < 0){
    bin <- 3
  } else if (distance < .5){
    bin <- 4
  } else if (distance < 1){
    bin <- 5
  } else {
    bin <- 6
  }
  C_12 <- rbind(C_12, c(bin))
}

#Hypothesis 12.5: C effected by distance to main chanel of the well, but with 4 groups:
C_12.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_mains[[wellname]])
  bin <- 0
  if (is.null(dist_to_mains[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 1
  } else if (distance < .5){
    bin <- 2
  } else {
    bin <- 3
  }
  C_12.5 <- rbind(C_12.5, c(bin))
}
```


```{r}
#C matrix restricted according to binned distance from nearest channel:
characteristics[,4] <- zscore(as.numeric(characteristics[,4]))
mean_near <- mean(as.numeric(characteristics[,4]))
#A dictionary for TWI of each well:
dist_to_nears <- hash()
for (rindex in 1:nrow(characteristics)){
  dist_to_nears[[characteristics[rindex, 1]]] <- characteristics[rindex, 4]
}

#Hypothesis 13: C effected by distance to nearest chanel:
C_13 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_nears[[wellname]])
  bin <- 0
  if (is.null(dist_to_nears[[wellname]])){
    bin <- 1
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 2
  } else if (distance < 0){
    bin <- 3
  } else if (distance < .5){
    bin <- 4
  } else if (distance < 1){
    bin <- 5
  } else {
    bin <- 6
  }
  C_13 <- rbind(C_13, c(bin))
}

#Hypothesis 13.5: C effected by distance to nearest chanel, but with 3 groups rather than 6:
C_13.5 = matrix(NA, nrow = 0, ncol = 1)
for (wellname in rownames(groundwater_variates_75)){
  distance <- as.numeric(dist_to_nears[[wellname]])
  bin <- 0
  if (is.null(dist_to_nears[[wellname]])){
    bin <- 2
    ###FIXME: some of the distances are not calculated, so I had to put in this case!
  } else if (distance < -.5){
    bin <- 1
  } else if (distance < .5){
    bin <- 2
  } else {
    bin <- 3
  }
  C_13.5 <- rbind(C_13.5, c(bin))
}
```
```{r}
df <- data.frame(x =1:10,
                 F =runif(10,1,2),
                 L =runif(10,0,1),
                 U =runif(10,2,3))

require(ggplot2)
ggplot(df, aes(x = x, y = F)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymax = U, ymin = L))

df2 <- data.frame(x =c("one", "two", "three", "four"),
                 "la" =c(1, 1, 3, 4),
                 L =c(0, -.5, 1, 1),
                 U =c(3,3,3.5,5))
ggplot(df2, aes(x = x, y = "la")) +
  geom_point(size = 1) +
  geom_errorbar(aes(ymax = U, ymin = L))

CIs_df <- data.frame(x =c("C-Riparian", "C-"),
                 F =c(-0.0677, 0.1147),
                 L =c(-0.1164, 0.0717),
                 U =c( -0.0190, 0.1576)
)
ggplot(CIs_df, aes(x = x, y = F)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymax = U, ymin = L))

CIs_df <- data.frame(x =c("C-Riparian", "C-Fan", "C-Terrace"),
                 F =c(0.0670, -0.1037,0.0798),
                 L =c(0.0206, -0.1720, -0.0231),
                 U =c( 0.1073, -0.0353, 0.1828)
)
ggplot(CIs_df, aes(x = x, y = F)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymax = U, ymin = L))

CIs_df <- data.frame(x =c("nearer", "near", "far", "farther"),
                 F =c(0.0961, -0.0940, 0.0697, -0.1348 ),
                 L =c(0.0539 , -0.1602 , -0.0323, -0.2451),
                 U =c( 0.1383, -0.0278, 0.1717, -0.0244)
)
ggplot(CIs_df, aes(x = x, y = F)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymax = U, ymin = L))

```





