library(sp)
library(jsonlite)

# Example usage
# ```
# # load Rdata file with ROIs generated by phenopix DrawMULTIROI function
# # (will create a new roi.data variable)
# load("data/phenocam/phenopix/RGB/roi.data.Rdata")
# # a specific roi from the loaded roi.data
# roi1 <- roi.data$roi1
# # Simplify the polygons for output
# polygons <- extract_polygons(roi1)
# # output them as json
# write_json(polygons, "data/roi1.json", pretty = TRUE)
# ```
extract_polygons <- function(spatial_polygons) {
  if (!inherits(spatial_polygons, "SpatialPolygons")) {
    stop("Input must be a SpatialPolygons object.")
  }

  # For each top-level polygon
  lapply(spatial_polygons@polygons, function(pg) {
    # Each polygon may consist of multiple rings
    lapply(pg@Polygons, function(p) {
      p@coords   # matrix with columns: x, y
    })
  })
}


extract_polygon_list_flat <- function(spatial_polygons) {
  polys_nested <- extract_polygons(spatial_polygons)
  unlist(polys_nested, recursive = FALSE)
}

# Orients the coordinates from bottom-left 0,0 to top-left 0,0
sp_to_top_left <- function(polygons, ymax) {
  lapply(polygons, function(poly) { 
    poly[,2] <- (ymax - 1) - poly[,2]
    poly
  })
}

# Take an ROI generated by phenopix library and output as
# simple list of polygons with top-left as 0,0 orientation
phenopix_roi_to_top_left_polygons <- function(roi) {
  ymax <- nrow(roi$mask)
  polygons <- extract_polygon_list_flat(roi$polygons)
  sp_to_top_left(polygons, ymax)
}

